version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web:latest
    restart: unless-stopped
    ports:
      - 3002:3002
    environment:
      AUTH_SECRET_KEY: passwd
      API_REVERSE_PROXY: http:/go-chatgpt-api:8080/conversation
      OPENAI_ACCESS_TOKEN: xxx
      #OPENAI_API_KEY: xxx

  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    restart: unless-stopped
